"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { Bot, History, LoaderCircle, MessageCircle, Plus, Send, Trash2, X } from "lucide-react";

type Message={id:string;role:"user"|"assistant";content:string};
type Conversation={id:string;title:string};
type Result={conversation_id:string;message:Message;follow_up_questions:string[];detail?:string};

function Markdown({content}:{content:string}) {
  const inline=(text:string)=>text.split(/(\*\*[^*]+\*\*)/g).map((part,index)=>part.startsWith("**")&&part.endsWith("**")?<strong key={index} className="font-semibold text-slate-100">{part.slice(2,-2)}</strong>:part);
  return <div className="space-y-2 text-xs leading-5 text-slate-300">{content.split("\n").map((line,index)=>line.startsWith("### ")?<h4 key={index} className="pt-1 text-sm font-semibold text-white">{line.slice(4)}</h4>:line.startsWith("- ")?<div key={index} className="flex gap-2"><span className="text-violet-400">•</span><span>{inline(line.slice(2))}</span></div>:line?<p key={index}>{inline(line)}</p>:<span key={index} className="block h-1"/>)}</div>;
}

export function SentinelAIChat(){
  const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[historyOpen,setHistoryOpen]=useState(false);
  const [input,setInput]=useState(""),[error,setError]=useState(""),[conversationId,setConversationId]=useState<string|null>(null);
  const [messages,setMessages]=useState<Message[]>([]),[followups,setFollowups]=useState<string[]>([]),[conversations,setConversations]=useState<Conversation[]>([]);
  const endRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const openChat=(event:Event)=>{setOpen(true);const prompt=(event as CustomEvent<{prompt?:string}>).detail?.prompt;if(prompt)setInput(prompt)};window.addEventListener("sentinel:open",openChat);return()=>window.removeEventListener("sentinel:open",openChat)},[]);
  useEffect(()=>{if(open)void loadHistory()},[open]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"})},[messages,loading]);
  async function loadHistory(){try{const response=await fetch("/api/ai/conversations");if(response.ok)setConversations(await response.json())}catch{/* non-blocking */}}
  async function loadConversation(id:string){setError("");try{const response=await fetch(`/api/ai/conversations/${id}`);const body=await response.json();if(!response.ok)throw new Error(body.detail);setConversationId(id);setMessages(body.messages);setHistoryOpen(false)}catch(reason){setError(reason instanceof Error?reason.message:"Could not load conversation")}}
  function newChat(){setConversationId(null);setMessages([]);setFollowups([]);setError("");setHistoryOpen(false)}
  async function clearChat(){if(!conversationId){newChat();return}try{const response=await fetch(`/api/ai/conversations/${conversationId}`,{method:"DELETE"});if(!response.ok)throw new Error("Could not clear chat");newChat();void loadHistory()}catch(reason){setError(reason instanceof Error?reason.message:"Could not clear chat")}}
  async function send(text=input){const value=text.trim();if(!value||loading)return;setMessages(items=>[...items,{id:`local-${Date.now()}`,role:"user",content:value}]);setInput("");setError("");setLoading(true);setFollowups([]);try{const response=await fetch("/api/ai/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:value,conversation_id:conversationId})});const body=await response.json() as Result;if(!response.ok)throw new Error(body.detail??"Sentinel AI is unavailable");setConversationId(body.conversation_id);setMessages(items=>[...items,body.message]);setFollowups(body.follow_up_questions);void loadHistory()}catch(reason){setError(reason instanceof Error?reason.message:"Sentinel AI is unavailable")}finally{setLoading(false)}}
  function submit(event:FormEvent){event.preventDefault();void send()}
  return <>
    <button type="button" onClick={()=>setOpen(true)} aria-label="Open Sentinel AI assistant" className="fixed bottom-5 right-5 z-40 flex items-center gap-2 rounded-full border border-violet-400/30 bg-violet-600 px-4 py-3 text-xs font-semibold text-white shadow-[0_14px_45px_rgba(124,58,237,.45)] transition hover:-translate-y-0.5 hover:bg-violet-500"><MessageCircle size={18}/> Sentinel AI</button>
    {open&&<div className="fixed inset-0 z-[70] bg-black/45 backdrop-blur-[2px] sm:bg-transparent sm:backdrop-blur-none" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section role="dialog" aria-modal="true" aria-label="Sentinel AI assistant" className="absolute inset-2 flex flex-col overflow-hidden rounded-2xl border border-slate-700 bg-[#0b111b] shadow-2xl sm:inset-auto sm:bottom-5 sm:right-5 sm:h-[min(720px,calc(100vh-40px))] sm:w-[430px]">
      <header className="flex items-center justify-between border-b border-slate-800 px-4 py-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-500/15 text-violet-400"><Bot size={19}/></span><div><h2 className="text-sm font-semibold text-white">Sentinel AI</h2><p className="text-[10px] text-emerald-400">Grounded in your organization data</p></div></div><div className="flex"><button onClick={()=>setHistoryOpen(value=>!value)} aria-label="Conversation history" className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><History size={16}/></button><button onClick={newChat} aria-label="New chat" className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><Plus size={16}/></button><button onClick={()=>setOpen(false)} aria-label="Close Sentinel AI" className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><X size={17}/></button></div></header>
      {historyOpen&&<div className="absolute inset-x-3 top-16 z-10 max-h-64 overflow-auto rounded-xl border border-slate-700 bg-[#111925] p-2 shadow-xl"><p className="px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-slate-500">Conversation history</p>{conversations.length?conversations.map(item=><button key={item.id} onClick={()=>void loadConversation(item.id)} className="block w-full truncate rounded-lg px-2 py-2 text-left text-xs text-slate-300 hover:bg-slate-800">{item.title}</button>):<p className="px-2 py-3 text-xs text-slate-500">No previous conversations.</p>}</div>}
      <div className="flex-1 space-y-4 overflow-y-auto p-4">{messages.length===0&&<div className="rounded-xl border border-violet-400/15 bg-violet-500/5 p-4"><Markdown content="Hi, I'm Sentinel AI. Ask me about your uploaded data, reports, KPIs, or how to use Sentinel."/><div className="mt-3 grid gap-2">{["Show total revenue","Which product performed best?","Summarize my data"].map(item=><button key={item} onClick={()=>void send(item)} className="rounded-lg border border-slate-800 px-3 py-2 text-left text-[11px] text-slate-400 hover:border-violet-500/40 hover:text-white">{item}</button>)}</div></div>}{messages.map(message=><div key={message.id} className={message.role==="user"?"ml-10 rounded-xl bg-violet-600 px-3 py-2.5 text-xs text-white":"mr-4 rounded-xl border border-slate-800 bg-slate-900/70 px-3 py-3"}>{message.role==="assistant"?<Markdown content={message.content}/>:message.content}</div>)}{loading&&<div role="status" className="mr-4 flex items-center gap-2 rounded-xl border border-slate-800 bg-slate-900/70 px-3 py-3 text-xs text-slate-400"><LoaderCircle className="animate-spin" size={15}/> Sentinel is analyzing verified data…</div>}{error&&<p role="alert" className="rounded-lg border border-red-500/20 bg-red-500/10 px-3 py-2 text-xs text-red-300">{error}</p>}{followups.map(item=><button key={item} onClick={()=>void send(item)} className="mr-2 rounded-full border border-slate-700 px-3 py-1.5 text-[10px] text-slate-400 hover:border-violet-500/50 hover:text-white">{item}</button>)}<div ref={endRef}/></div>
      <form onSubmit={submit} className="border-t border-slate-800 p-3"><div className="flex items-end gap-2 rounded-xl border border-slate-700 bg-slate-950/60 p-2 focus-within:border-violet-500/60"><textarea value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send()}}} aria-label="Message Sentinel AI" placeholder="Ask about data, reports, KPIs, or Sentinel…" rows={2} className="max-h-28 flex-1 resize-none bg-transparent px-1 py-1 text-xs text-white outline-none placeholder:text-slate-600"/><button disabled={!input.trim()||loading} aria-label="Send message" className="grid h-9 w-9 place-items-center rounded-lg bg-violet-600 text-white disabled:opacity-40"><Send size={15}/></button></div><div className="mt-2 flex justify-between"><p className="text-[9px] text-slate-600">Numbers come from verified tenant data.</p><button type="button" onClick={()=>void clearChat()} className="flex items-center gap-1 text-[9px] text-slate-600 hover:text-red-400"><Trash2 size={10}/>Clear chat</button></div></form>
    </section></div>}
  </>;
}
