"use client";

import { Check, Copy, Download, Mail, MessageCircle, Share2, Smartphone, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";

type ReportAsset = { id: string; original_name?: string; detail?: string };

export function ClassicDashboardActions() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [working, setWorking] = useState(false);
  const [shareFile, setShareFile] = useState<File | null>(null);
  const [message, setMessage] = useState("");
  const reportPromise = useRef<Promise<ReportAsset> | null>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!menuOpen) return;
    const close = (event: MouseEvent) => { if (!menuRef.current?.contains(event.target as Node)) setMenuOpen(false); };
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setMenuOpen(false); };
    document.addEventListener("mousedown", close); document.addEventListener("keydown", escape);
    return () => { document.removeEventListener("mousedown", close); document.removeEventListener("keydown", escape); };
  }, [menuOpen]);

  function ensureReport() {
    if (!reportPromise.current) reportPromise.current = fetch("/api/files/reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }).then(async response => {
      const asset = await response.json() as ReportAsset;
      if (!response.ok || !asset.id) throw new Error(asset.detail ?? "Report generation failed");
      return asset;
    }).catch(error => { reportPromise.current = null; throw error; });
    return reportPromise.current;
  }

  function openMenu() {
    setMessage("");
    setMenuOpen(value => !value);
    if (!shareFile) void getReportFile().then(({ file }) => setShareFile(file)).catch(() => setMessage("Unable to prepare the report."));
  }
  async function getReportFile() { const asset = await ensureReport(); const response = await fetch(`/api/files/${asset.id}?download=1`); if (!response.ok) throw new Error("Report download failed"); const blob = await response.blob(); return { asset, file: new File([blob], asset.original_name ?? "sentinel-executive-report.pdf", { type: "application/pdf" }) }; }

  function shareToApps() {
    if (!shareFile) return;
    setWorking(true); setMessage("");
    const payload: ShareData = { title: "Sentinel AI Executive Report", text: "Secure executive business intelligence report generated by Sentinel AI.", files: [shareFile] };
    const hasNativeShare = typeof navigator.share === "function";
    const canShareFile = typeof navigator.canShare !== "function" || navigator.canShare(payload);
    const operation = hasNativeShare && canShareFile
      ? navigator.share(payload)
      : hasNativeShare
        ? navigator.share({ title: payload.title, text: payload.text, url: location.href })
        : navigator.clipboard.writeText(location.href).then(() => setMessage("Link copied. Attach the downloaded PDF in your preferred app."));
    void operation.catch(error => {
      if (!(error instanceof DOMException && error.name === "AbortError")) setMessage(error instanceof Error ? error.message : "Sharing failed");
    }).finally(() => setWorking(false));
  }
  function shareWhatsApp() { const text = encodeURIComponent(`Sentinel AI Executive Report\n${location.href}`); window.open(`https://wa.me/?text=${text}`, "_blank", "noopener,noreferrer"); }
  function shareEmail() { location.href = `mailto:?subject=${encodeURIComponent("Sentinel AI Executive Report")}&body=${encodeURIComponent(`View the secure report: ${location.href}`)}`; }
  async function copyLink() { await navigator.clipboard.writeText(location.href); setMessage("Secure report link copied"); }
  async function exportPdf() {
    setWorking(true); setMessage("");
    try {
      const asset = await ensureReport();
      const link = document.createElement("a");
      link.href = `/api/files/${asset.id}?download=1`;
      link.download = asset.original_name ?? "sentinel-executive-report.pdf";
      document.body.appendChild(link); link.click(); link.remove();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Export failed"); }
    finally { setWorking(false); }
  }

  return <div ref={menuRef} className="relative flex items-center gap-2">
    <button type="button" aria-expanded={menuOpen} aria-haspopup="menu" onClick={openMenu} className="flex h-10 items-center gap-2 rounded-lg border border-slate-800 bg-slate-900 px-3 text-xs text-slate-300"><Share2 size={15}/> Share Report</button>
    <button type="button" disabled={working} onClick={() => void exportPdf()} className="flex h-10 items-center gap-2 rounded-lg bg-violet-600 px-3 text-xs font-medium text-white hover:bg-violet-500 disabled:opacity-60"><Download size={15}/> {working ? "Preparing..." : "Export PDF"}</button>
    {menuOpen && <div role="menu" aria-label="Share report" className="absolute right-0 top-12 z-50 w-72 rounded-xl border border-slate-700 bg-[#101722] p-2 shadow-2xl shadow-black/50">
      <div className="flex items-start justify-between px-2 py-2"><div><p className="text-xs font-semibold text-white">Share executive report</p><p className="mt-1 text-[10px] leading-4 text-slate-500">Native sharing can attach the private PDF to installed apps.</p></div><button type="button" aria-label="Close sharing menu" onClick={() => setMenuOpen(false)} className="text-slate-500 hover:text-white"><X size={15}/></button></div>
      <button role="menuitem" disabled={working || !shareFile} onClick={shareToApps} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-xs text-slate-300 hover:bg-slate-800 disabled:opacity-50"><Smartphone size={16} className="text-violet-400"/><span><strong className="block font-medium">{shareFile ? "Share to apps" : "Preparing secure PDF..."}</strong><span className="mt-0.5 block text-[10px] text-slate-500">WhatsApp, Instagram, Teams, and more</span></span></button>
      <button role="menuitem" onClick={shareWhatsApp} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-xs text-slate-300 hover:bg-slate-800"><MessageCircle size={16} className="text-emerald-400"/>WhatsApp message</button>
      <button role="menuitem" onClick={shareEmail} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-xs text-slate-300 hover:bg-slate-800"><Mail size={16} className="text-sky-400"/>Email report link</button>
      <button role="menuitem" onClick={() => void copyLink()} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-xs text-slate-300 hover:bg-slate-800"><Copy size={16} className="text-amber-400"/>Copy secure link</button>
      {message && <p role="status" className="mx-2 mt-1 flex items-center gap-2 rounded-lg bg-slate-950/60 px-3 py-2 text-[10px] text-slate-400"><Check size={12} className="text-emerald-400"/>{message}</p>}
    </div>}
  </div>;
}
