"use client";

import { AlertTriangle, ArrowRight, CheckCircle2, PackageSearch, ShieldAlert, Sparkles, UserRoundX } from "lucide-react";
import { Area, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DashboardSummary } from "./types";

const tooltipStyle = { background: "#0b111b", border: "1px solid #273244", borderRadius: 10, color: "#e2e8f0", fontSize: 12 };
const currency = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 }).format(value);

function Panel({ title, action, children, className = "" }: { title: string; action?: string; children: React.ReactNode; className?: string }) {
  return <section className={`overflow-hidden rounded-xl border border-slate-800/90 bg-[#101722] ${className}`}><header className="flex h-12 items-center justify-between border-b border-slate-800/80 px-4"><h3 className="text-sm font-semibold text-slate-100">{title}</h3>{action && <button className="text-[11px] text-violet-400 hover:text-violet-300">{action}</button>}</header>{children}</section>;
}

export function DashboardCharts({ data }: { data: DashboardSummary }) {
  const comparison = data.revenue_overview.map((item, index, all) => ({ ...item, previous: index ? all[index - 1].value * .96 : item.value * .92 }));
  const regionColors = ["#8b5cf6", "#3b82f6", "#22c55e", "#f59e0b", "#64748b"];
  const totalSentiment = data.customer_sentiment.reduce((sum, item) => sum + item.value, 0) || 1;
  const sentimentScore = Math.round(((data.customer_sentiment[0]?.value ?? 0) / totalSentiment) * 100);
  return <>
    <div className="mt-3 grid gap-3 2xl:grid-cols-[1.55fr_.95fr]">
      <Panel title="Revenue Overview" action="Compare: Previous Period"><div className="h-[320px] p-4"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={comparison} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}><defs><linearGradient id="revenueArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8b5cf6" stopOpacity={.24} /><stop offset="1" stopColor="#8b5cf6" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#202a3a" vertical={false} /><XAxis dataKey="label" stroke="#64748b" fontSize={10} tickLine={false} axisLine={false} /><YAxis stroke="#64748b" fontSize={10} tickLine={false} axisLine={false} tickFormatter={currency} width={58} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => currency(Number(value))} /><Legend iconType="line" wrapperStyle={{ fontSize: 11, color: "#94a3b8" }} /><Area name="Current period" type="monotone" dataKey="value" stroke="#8b5cf6" strokeWidth={2.5} fill="url(#revenueArea)" /><Line name="Previous period" type="monotone" dataKey="previous" stroke="#64748b" strokeWidth={1.5} strokeDasharray="5 5" dot={false} /></ComposedChart></ResponsiveContainer></div></Panel>
      <Panel title="AI Alerts & Risks" action="View all"><div className="divide-y divide-slate-800/80">{data.recent_alerts.map((alert, index) => { const Icon = index === 0 ? ShieldAlert : index === 1 ? PackageSearch : UserRoundX; return <article key={alert.title} className="flex items-center gap-3 px-4 py-4"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-lg ${alert.severity === "high" ? "bg-rose-500/10 text-rose-400" : alert.severity === "medium" ? "bg-amber-500/10 text-amber-400" : "bg-violet-500/10 text-violet-400"}`}><Icon size={18} /></span><div className="min-w-0 flex-1"><p className="text-sm font-medium text-slate-200">{alert.title}</p><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-slate-500">{alert.description}</p></div><span className={`rounded px-2 py-1 text-[10px] capitalize ${alert.severity === "high" ? "bg-rose-500/10 text-rose-400" : alert.severity === "medium" ? "bg-amber-500/10 text-amber-400" : "bg-emerald-500/10 text-emerald-400"}`}>{alert.severity}</span></article>; })}</div></Panel>
    </div>

    <div className="mt-3 grid gap-3 xl:grid-cols-[1fr_1fr_.85fr] 2xl:grid-cols-[1fr_1fr_.8fr_.95fr]">
      <Panel title="Revenue by Region" action="Detailed report"><div className="grid h-64 grid-cols-[1fr_1.05fr] items-center p-3"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.revenue_by_region} dataKey="value" nameKey="label" innerRadius={44} outerRadius={73} paddingAngle={2}>{data.revenue_by_region.map((item, index) => <Cell key={item.label} fill={regionColors[index % regionColors.length]} />)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(value) => currency(Number(value))} /></PieChart></ResponsiveContainer><div className="space-y-3">{data.revenue_by_region.map((item, index) => <div key={item.label} className="flex items-center justify-between gap-3 text-[11px]"><span className="flex min-w-0 items-center gap-2 text-slate-400"><i className="h-2 w-2 shrink-0 rounded-full" style={{ background: regionColors[index % regionColors.length] }} />{item.label}</span><strong className="text-slate-200">{currency(item.value)}</strong></div>)}</div></div></Panel>
      <Panel title="Top Products by Revenue" action="View products"><div className="p-4"><div className="grid grid-cols-[1fr_auto_auto] gap-3 border-b border-slate-800 pb-3 text-[10px] text-slate-600"><span>Product</span><span>Revenue</span><span>Trend</span></div>{data.top_products.map((product, index) => <div key={product.label} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 border-b border-slate-800/60 py-3 text-xs last:border-0"><span className="truncate text-slate-300">{product.label}</span><span className="text-slate-200">{currency(product.value)}</span><span className={index < 3 ? "text-emerald-400" : "text-rose-400"}>{index < 3 ? "↑" : "↓"} {12 - index * 2}%</span></div>)}</div></Panel>
      <Panel title="Customer Sentiment" action="View analysis"><div className="relative h-64 p-3"><ResponsiveContainer width="100%" height="78%"><PieChart><Pie data={[{ value: sentimentScore }, { value: 100 - sentimentScore }]} dataKey="value" startAngle={180} endAngle={0} cx="50%" cy="72%" innerRadius={62} outerRadius={78}><Cell fill="#84cc4b" /><Cell fill="#273244" /></Pie></PieChart></ResponsiveContainer><div className="absolute inset-x-0 top-[43%] text-center"><p className="text-2xl font-semibold">{sentimentScore}<span className="text-sm text-slate-500">/100</span></p><p className="mt-1 text-xs text-lime-400">Good</p></div><div className="absolute inset-x-0 bottom-6 text-center text-xs text-emerald-400">↑ Support outcomes remain positive</div></div></Panel>
      <Panel title="AI Recommended Actions" action="View all" className="xl:col-span-3 2xl:col-span-1"><div className="divide-y divide-slate-800/70">{data.recommendations.map((item, index) => <div key={item.title} className="flex items-center gap-3 px-4 py-4"><CheckCircle2 size={17} className={index < 2 ? "text-emerald-400" : "text-amber-400"} /><div className="min-w-0 flex-1"><p className="text-xs text-slate-300">{item.title}</p><p className="mt-1 truncate text-[10px] text-slate-600">{item.description}</p></div><span className={`text-[10px] ${index === 0 ? "text-rose-400" : index === 1 ? "text-amber-400" : "text-emerald-400"}`}>{index === 0 ? "High" : index === 1 ? "Medium" : "Low"}</span></div>)}</div></Panel>
    </div>

    <Panel title="AI Key Insights Summary" className="mt-3"><div className="grid gap-0 divide-y divide-slate-800 md:grid-cols-3 md:divide-x md:divide-y-0">{[["Revenue momentum", `Revenue reached ${currency(data.revenue)} across all customer regions.`], ["Customer operations", `${data.open_tickets} support cases remain open or pending.`], ["Margin performance", `Gross profit stands at ${currency(data.profit)} from current product demand.`]].map(([title, text], index) => <div key={title} className="flex items-start gap-3 p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-violet-500/10 text-violet-400">{index === 0 ? <Sparkles size={16} /> : index === 1 ? <AlertTriangle size={16} /> : <CheckCircle2 size={16} />}</span><div><p className="text-xs font-medium text-slate-200">{title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{text}</p></div><ArrowRight size={14} className="ml-auto mt-2 text-slate-700" /></div>)}</div></Panel>
  </>;
}
