"use client";

import { AlertTriangle, ArrowRight, Check, CloudUpload, Database, FileSpreadsheet, LoaderCircle, RotateCcw, ShieldCheck, Trash2 } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { DragEvent, Suspense, useCallback, useEffect, useState } from "react";

const HEADERS = ["Date", "Revenue", "Orders", "Cancelled", "Region", "Product", "Customer"];
type ImportItem = { id: string; file_name: string; mode: string; status: string; total_rows: number; processed_rows: number; imported_rows: number; progress_percent: number; error_message?: string; created_at: string; completed_at?: string };
type DatasetStatus = { has_data: boolean; record_count: number; active_import?: ImportItem | null; history: ImportItem[] };

function parseLine(line: string) { const values: string[] = []; let current = "", quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; if (char === '"' && line[i + 1] === '"') { current += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { values.push(current); current = ""; } else current += char; } values.push(current); return values; }

function OnboardingContent() {
  const router = useRouter(); const searchParams = useSearchParams(); const managing = searchParams.get("manage") === "1"; const selecting = searchParams.get("select") === "1";
  const [status, setStatus] = useState<DatasetStatus | null>(null); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<string[][]>([]); const [rows, setRows] = useState(0); const [error, setError] = useState(""); const [uploadProgress, setUploadProgress] = useState(0); const [busy, setBusy] = useState(false); const [mode, setMode] = useState<"initial" | "append" | "replace">("initial"); const [dragging, setDragging] = useState(false);
  const loadStatus = useCallback(async () => { const response = await fetch("/api/datasets", { cache: "no-store" }); if (response.status === 401) { router.replace("/login?expired=1"); return null; } const data = await response.json() as DatasetStatus & { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "Dataset status unavailable"); setStatus(data); if (data.has_data) setMode(current => current === "initial" ? "replace" : current); return data; }, [router]);
  useEffect(() => { void loadStatus().catch(cause => setError(cause instanceof Error ? cause.message : "Unable to load dataset status")); }, [loadStatus]);
  useEffect(() => { if (!status?.active_import) return; const timer = window.setInterval(() => void loadStatus(), 800); return () => window.clearInterval(timer); }, [status?.active_import, loadStatus]);
  useEffect(() => { const completed = status?.history[0]; if (busy && completed?.status === "completed" && !status?.active_import) { setBusy(false); router.replace("/dashboard"); router.refresh(); } if (completed?.status === "failed" && busy) { setBusy(false); setError(completed.error_message ?? "Import failed and all changes were rolled back."); } }, [status, busy, router]);

  async function selectFile(candidate: File) { setError(""); const extension=candidate.name.toLowerCase().split(".").pop(); if (!["csv","xlsx"].includes(extension??"")) { setFile(null); setError("Choose a CSV or Excel file using the required Sentinel AI headers."); return; } if (candidate.size > 10 * 1024 * 1024) { setError("The file exceeds the configured 10 MB upload limit."); return; } if(extension==="xlsx"){setFile(candidate);setRows(0);setPreview([]);return} const text = await candidate.text(); const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean); const headers = parseLine(lines[0] ?? ""); const missing=HEADERS.filter(header=>!headers.includes(header)); if (missing.length) { setError(`Missing required headers: ${missing.join(", ")}`); return; } if (lines.length < 2) { setError("The CSV contains no business records."); return; } const requiredIndexes=HEADERS.map(header=>headers.indexOf(header)); setFile(candidate); setRows(lines.length - 1); setPreview(lines.slice(1, 6).map(line=>{const values=parseLine(line);return requiredIndexes.map(index=>values[index]??"")})); }
  function drop(event: DragEvent) { event.preventDefault(); setDragging(false); const candidate = event.dataTransfer.files[0]; if (candidate) void selectFile(candidate); }
  function upload() { if (!file) return; setBusy(true); setError(""); setUploadProgress(0); const xhr = new XMLHttpRequest(); xhr.open("POST", "/api/datasets"); xhr.setRequestHeader("Content-Type", "text/csv"); xhr.setRequestHeader("X-Filename", file.name); xhr.setRequestHeader("X-Import-Mode", status?.has_data ? mode : "initial"); xhr.upload.onprogress = event => { if (event.lengthComputable) setUploadProgress(Math.round(event.loaded * 100 / event.total)); }; xhr.onerror = () => { setBusy(false); setError("The upload connection failed. Please retry."); }; xhr.onload = async () => { let result: { detail?: string } = {}; try { result = JSON.parse(xhr.responseText); } catch {} if (xhr.status < 200 || xhr.status >= 300) { setBusy(false); setError(result.detail ?? "The dataset was rejected."); return; } setUploadProgress(100); await loadStatus(); }; xhr.send(file); }
  async function deleteDataset() { if (!confirm("Delete every imported business record for this organization? This cannot be undone.")) return; setBusy(true); const response = await fetch("/api/datasets", { method: "DELETE" }); if (!response.ok) { const result = await response.json(); setError(result.detail ?? "Dataset deletion failed"); } else { setFile(null); setPreview([]); setRows(0); await loadStatus(); } setBusy(false); }
  const active = status?.active_import; const progress = active?.progress_percent ?? uploadProgress;

  return <main className="min-h-screen bg-[#070c14] px-4 py-6 text-slate-100 sm:px-6 lg:px-10"><div className="mx-auto max-w-6xl">
    <header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl border border-violet-400/25 bg-violet-500/10 text-violet-300"><Database size={21}/></span><div><p className="font-semibold">Sentinel AI</p><p className="text-xs text-slate-500">Secure dataset onboarding</p></div></div>{status?.has_data && <button onClick={() => router.push("/dashboard")} className="rounded-xl border border-slate-700 px-4 py-2 text-sm text-slate-300 hover:bg-slate-800">Return to dashboard</button>}</header>
    <section className="mx-auto mt-10 max-w-3xl text-center"><div className="mx-auto mb-5 flex w-fit items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/5 px-3 py-1.5 text-xs text-emerald-300"><ShieldCheck size={14}/> Organization-isolated import</div><h1 className="text-3xl font-semibold tracking-[-.035em] sm:text-5xl">{managing ? "Manage your business dataset" : selecting ? "Choose data for this session" : "Connect your data to Sentinel AI"}</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-slate-400 sm:text-base">{selecting ? "Continue with your saved organization dataset, or browse a new file to replace or extend it. You stay in control after every login." : "Your dashboard remains private and empty until your organization imports its own validated CSV. Data is processed transactionally and never shared with another company."}</p></section>
    {selecting && status?.has_data && <section className="mx-auto mt-8 grid max-w-3xl gap-3 sm:grid-cols-2"><button onClick={() => router.push("/dashboard")} className="rounded-2xl border border-emerald-400/25 bg-emerald-400/10 p-5 text-left transition hover:border-emerald-300/50 hover:bg-emerald-400/15"><span className="flex items-center gap-2 text-sm font-semibold text-emerald-200"><Database size={17}/>Use saved dataset</span><span className="mt-2 block text-xs leading-5 text-slate-400">Open {status.record_count.toLocaleString()} saved records from {status.history[0]?.file_name ?? "your previous import"}.</span></button><label htmlFor="dataset-file" className="cursor-pointer rounded-2xl border border-violet-400/25 bg-violet-400/10 p-5 text-left transition hover:border-violet-300/50 hover:bg-violet-400/15"><span className="flex items-center gap-2 text-sm font-semibold text-violet-200"><CloudUpload size={17}/>Browse a new file</span><span className="mt-2 block text-xs leading-5 text-slate-400">Select a CSV to replace the saved dataset or append additional records.</span></label></section>}
    {status?.has_data && <section className="mx-auto mt-8 grid max-w-3xl gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-500">Current records</p><p className="mt-2 text-2xl font-semibold">{status.record_count.toLocaleString()}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-500">Last import</p><p className="mt-2 truncate text-sm font-medium">{status.history[0]?.file_name ?? "—"}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs text-slate-500">Data isolation</p><p className="mt-2 text-sm font-medium text-emerald-300">Tenant protected</p></div></section>}
    <section className="mx-auto mt-6 max-w-3xl rounded-3xl border border-slate-800 bg-slate-900/55 p-4 shadow-2xl shadow-black/20 sm:p-7">
      {status?.has_data && <div className="mb-5 flex flex-wrap gap-2"><button onClick={() => setMode("replace")} className={`rounded-lg px-4 py-2 text-xs ${mode === "replace" ? "bg-violet-600 text-white" : "border border-slate-700 text-slate-400"}`}>Replace dataset</button><button onClick={() => setMode("append")} className={`rounded-lg px-4 py-2 text-xs ${mode === "append" ? "bg-violet-600 text-white" : "border border-slate-700 text-slate-400"}`}>Append records</button><button disabled={busy} onClick={() => void deleteDataset()} className="ml-auto flex items-center gap-2 rounded-lg border border-rose-500/25 px-4 py-2 text-xs text-rose-300"><Trash2 size={14}/>Delete all data</button></div>}
      <label htmlFor="dataset-file" onDragEnter={event => {event.preventDefault(); setDragging(true)}} onDragOver={event => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={drop} className={`grid min-h-64 cursor-pointer place-items-center rounded-2xl border-2 border-dashed p-8 text-center transition ${dragging ? "border-violet-400 bg-violet-500/10" : "border-slate-700 bg-slate-950/45 hover:border-violet-500/60"}`}><span><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-violet-500/10 text-violet-300"><CloudUpload size={27}/></span><span className="mt-5 block text-base font-medium">Drop your CSV here</span><span className="mt-2 block text-sm text-slate-500">or click to browse · CSV only · maximum 10 MB</span><span className="mt-4 inline-block rounded-lg bg-white px-4 py-2 text-xs font-semibold text-slate-950">Browse file</span></span><input id="dataset-file" type="file" accept=".csv,text/csv" className="sr-only" onChange={event => { const selected = event.target.files?.[0]; if (selected) void selectFile(selected); }}/></label>
      {file && <div className="mt-4 flex items-center gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4"><FileSpreadsheet className="text-emerald-300"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{file.name}</p><p className="mt-1 text-xs text-slate-500">{rows.toLocaleString()} records · {(file.size / 1024 / 1024).toFixed(2)} MB · validation passed</p></div><Check className="text-emerald-300"/></div>}
      {error && <div role="alert" className="mt-4 flex gap-3 rounded-xl border border-rose-500/20 bg-rose-500/5 p-4 text-sm text-rose-200"><AlertTriangle className="shrink-0" size={18}/><span>{error}</span></div>}
      {(busy || active) && <div className="mt-5"><div className="flex justify-between text-xs"><span className="text-slate-400">{active ? `${active.status === "queued" ? "Preparing" : "Importing"} ${active.total_rows.toLocaleString()} records` : "Uploading securely"}</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400 transition-all" style={{width:`${Math.max(2, progress)}%`}}/></div><p className="mt-2 text-[11px] text-slate-600">You can keep this page open while background validation and batch inserts complete.</p></div>}
      {preview.length > 0 && <div className="mt-6 overflow-hidden rounded-xl border border-slate-800"><div className="flex items-center justify-between border-b border-slate-800 px-4 py-3"><p className="text-xs font-medium">Dataset preview</p><p className="text-[10px] text-slate-500">First {preview.length} records</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-[11px]"><thead className="bg-slate-950/70 text-slate-500"><tr>{HEADERS.map(header => <th key={header} className="whitespace-nowrap px-3 py-2 font-medium">{header}</th>)}</tr></thead><tbody>{preview.map((row,index) => <tr key={index} className="border-t border-slate-800/70">{row.map((cell,cellIndex)=><td key={cellIndex} className="max-w-40 truncate whitespace-nowrap px-3 py-2.5 text-slate-300">{cell}</td>)}</tr>)}</tbody></table></div></div>}
      <button disabled={!file || busy || !!active} onClick={upload} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-violet-600 text-sm font-semibold transition hover:bg-violet-500 disabled:cursor-not-allowed disabled:opacity-40">{busy || active ? <><LoaderCircle className="animate-spin" size={17}/>Processing dataset</> : <>{status?.has_data ? mode === "append" ? "Append validated records" : "Replace current dataset" : "Import and build dashboard"}<ArrowRight size={17}/></>}</button>
    </section>
    {status?.history?.length ? <section className="mx-auto mt-6 max-w-3xl rounded-2xl border border-slate-800 bg-slate-900/40 p-5"><h2 className="text-sm font-semibold">Import history</h2><div className="mt-3 space-y-2">{status.history.map(item => <div key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-slate-800 px-3 py-3 text-xs"><RotateCcw size={14} className="text-violet-300"/><span className="min-w-0 flex-1 truncate">{item.file_name}</span><span className="text-slate-500">{item.mode}</span><span className={item.status === "completed" ? "text-emerald-300" : item.status === "failed" ? "text-rose-300" : "text-amber-300"}>{item.status}</span><span className="text-slate-500">{item.imported_rows.toLocaleString()} imported</span><span className="text-slate-600">{new Date(item.created_at).toLocaleString()}</span></div>)}</div></section> : null}
    <label className="mx-auto mt-4 block max-w-3xl cursor-pointer text-center text-xs text-violet-300 hover:text-violet-200">Import an Excel (.xlsx) workbook<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="sr-only" onChange={event=>{const selected=event.target.files?.[0];if(selected)void selectFile(selected)}}/></label>
  </div></main>;
}

export default function OnboardingPage() { return <Suspense fallback={<main className="grid min-h-screen place-items-center bg-[#070c14] text-slate-400"><LoaderCircle className="animate-spin"/></main>}><OnboardingContent/></Suspense>; }
